package _19_day_异常._05_throws的方式处理异常;

public class throw的概述以及和throws的区别 {
    /*
    * A:throw的概述
    * 在功能方法内部出现某种情况，程序不能继续运行，需要进行跳转时，就用throw把异常对象抛出。
* B:案例演示
    * 分别演示编译时异常对象和运行时异常对象的抛出
* C:throws和throw的区别
    * a:throws
        * 用在方法声明后面，跟的是异常类名
        * 可以跟多个异常类名，用逗号隔开
        * 表示抛出异常，由该方法的调用者来处理
    * b:throw
        * 用在方法体内，跟的是异常对象名
        * 只能抛出一个异常对象名
        * 表示抛出异常，由方法体内的语句处理

     */
}
